/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
	public static AppController Controller = new AppController();
	
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Controller.start();
    }
}
